name: Sync Submodules and Mirror

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}  # Only works if submodules are in same org/account

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "abhishekhsaini7@gmail.com"

      - name: Rewrite submodule URLs with token (if secret is set)
        env:
          SUBMODULE_PAT: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
        run: |
          if [ -n "$SUBMODULE_PAT" ]; then
            echo "Injecting token into .gitmodules..."
            sed -i "s|https://github.com/|https://x-access-token:${SUBMODULE_PAT}@github.com/|g" .gitmodules
            git submodule sync
            git submodule update --init --recursive
          else
            echo "No submodule token provided. Assuming public or same-org private access."
          fi

      - name: Check which submodules changed (optional logging)
        run: |
          git submodule foreach 'echo "--- $name ---"; git status; git diff'

      - name: Run code checks (replace this block as needed)
        run: |
          echo "Running sample code checks..."
          # Add real checks here, like:
          # npm ci && npm run lint
          # mvn verify
          echo "Checks passed."

      - name: Push to mirror repo
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/abhishek2acc/repo-tp-pull-content.git
          git push mirror main --force
